POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "test1",
    "password": "test1"
}

###

POST http://localhost:3000/auth/signIn
Content-Type: application/json

{
    "email": "test1",
    "password": "test1"
}

###