POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "",
    "password": ""
}

###

POST http://localhost:3000/auth/signIn
Content-Type: application/json

{
    "email": "admin",
    "password": "admin"
}

###

GET http://localhost:3000/api/users/3
Content-Type: application/json
Authorization: Bearer 

###

PUT http://localhost:3000/api/users/3
Content-Type: application/json
Authorization: Bearer 

{
    "password": "newPassword"
}

###

DELETE http://localhost:3000/api/users/3
Content-Type: application/json
Authorization: Bearer 

###

POST http://localhost:3000/api/apps/3
Content-Type: application/json
Authorization: Bearer 

{
    "job_title" : "Software Engineer",
    "company_name" : "Amazon",
    "application_status" : "Under Review"
}

###

GET http://localhost:3000/api/apps/3
Content-Type: application/json
Authorization: Bearer 
###

GET http://localhost:3000/api/3/app/1
Content-Type: application/json
Authorization: Bearer 

###

PUT http://localhost:3000/api/3/app/1
Content-Type: application/json
Authorization: Bearer 

{
    "job_title" : "JOB_TITLE"
}


###

DELETE http://localhost:3000/api/3/app/2
Content-Type: application/json
Authorization: Bearer 
###
