POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "",
    "password": ""
}

###

POST http://localhost:3000/auth/signIn
Content-Type: application/json

{
    "email": "",
    "password": ""
}

###

GET http://localhost:3000/api/users/:userId
Content-Type: application/json
Authorization: Bearer 

###

PUT http://localhost:3000/api/users/:userId
Content-Type: application/json
Authorization: Bearer 

{
    
}

###

DELETE http://localhost:3000/api/users/:userId
Content-Type: application/json
Authorization: Bearer 